name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs: 
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore
      run: dotnet restore ./Todos.WebApi2.sln 
      
    - name : Build
      run: dotnet build ./Todos.WebApi2.sln --configuration Release

    - name : Publish 
      run: dotnet publish ./Todos.WebApi2/Todos.WebApi2.csproj --configuration Release --no-build --output './publish'

    - name : Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name : my-to-do-app2
        publish-profile : ${{secrets.AZURE_PUBLISH_PROFILE}}
        package: './publish'
